language: node_js
node_js:
  - 8
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  bucket: laszlo-hornyak.com
  region: eu-central-1
  skip_cleanup: true
  local_dir: dist